### ISSUE TITLE
feat: 🔒 Private repos

### ISSUE THREAD

**Issue by ieedan** [ieedan/jsrepo#155]
Working on this right now as it seems to be a pretty popular topic of discussion.

## Tasks
- [x] add `auth` command
- [x] move any file fetches to `git-providers`
- [ ] Add option to setup token when adding repos in `init`
- [ ] (maybe) improve errors when no credentials are supplied (this is hard because you normally get a 404)

**Comment by arielonoriaga** [comment]
👍🏻
